public class Main {
    public static void main(String[] args){
        String nature1="waterfall";
        String nature2="rain";
        String nature3="animals";
        String nature4="human";
        String nature5="fire";
        String nature6="water";
        String nature7="air";
        String nature8="earth";
        String nature9="ice";
        String space1="sun";
        String space2="jupiter";
        String space3="earth";
        String space4="milky way";
        String space5="galaxy";
        String space6="stars";
        String space7="satellite";
        String space8="rocket";
        String space9="cosmonaut";
        String cars1="Toyota";
        String cars2="Honda";
        String cars3="Mersedes";
        String cars4="Lexus";
        String cars5="Tesla";
        String cars6="Kia";
        String cars7="Ford";
        String cars8="Ferrari";
        String cars9="Lamborghini";
        String religion1="belief";
        String religion2="religious";
        String religion3="Muslim";
        String religion4="Christian";
        String religion5="Buddhist";
        String religion6="faith";
        String religion7="believe";
        String religion8="angel";
        String religion9="holy";
        String love1="marry";
        String love2="love";
        String love3="husband";
        String love4="youth";
        String love5="hug";
        String love6="couple";
        String love7="relationship";
        String love8="date";
        String love9="family";
        System.out.println(nature1);
        System.out.println(nature2);
        System.out.println(nature3);
        System.out.println(nature4);
        System.out.println(nature5);
        System.out.println(nature6);
        System.out.println(nature7);
        System.out.println(nature8);
        System.out.println(nature9);
        System.out.println(space1);
        System.out.println(space2);
        System.out.println(space3);
        System.out.println(space4);
        System.out.println(space5);
        System.out.println(space6);
        System.out.println(space7);
        System.out.println(space8);
        System.out.println(space9);
        System.out.println(cars1);
        System.out.println(cars2);
        System.out.println(cars3);
        System.out.println(cars4);
        System.out.println(cars5);
        System.out.println(cars6);
        System.out.println(cars7);
        System.out.println(cars8);
        System.out.println(cars9);
        System.out.println(religion1);
        System.out.println(religion2);
        System.out.println(religion3);
        System.out.println(religion4);
        System.out.println(religion5);
        System.out.println(religion6);
        System.out.println(religion7);
        System.out.println(religion8);
        System.out.println(religion9);
        System.out.println(love1);
        System.out.println(love2);
        System.out.println(love3);
        System.out.println(love4);
        System.out.println(love5);
        System.out.println(love6);
        System.out.println(love7);
        System.out.println(love8);
        System.out.println(love9);
    }
}
